#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/1/26 13:40
# @Author  : ZQY
# @Site    : 
# @File    : clawer_v1.py
# @Software: PyCharm


# !/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/1/25 8:07
# @Author  : ZQY
# @Site    :
# @File    : clawer.py
# @Software: PyCharm

from bs4 import BeautifulSoup
import requests

default_url = 'http://58.192.29.142/simscxall/Default.aspx'
userRecord_url = 'http://58.192.29.142/simscxall/usedRecord.aspx'

# 创建一个Session会话
session = requests.Session()


# r = session.get(default_url)
# soup = BeautifulSoup(r.content, 'lxml')
# VIEWSTATE = soup.find(id='__VIEWSTATE')['value']


def get_html(drxiaoqu='2', drlouming='63', drfangjian='2064', radio='usedR', txtstart='2018-01-01', txtend='2018-01-17'):

    VIEWSTATE = '/wEPDwUJLTI5NzY1NzY0D2QWAgIBD2QWCAIBDxBkDxYEZgIBAgICAxYEEAUG5qCh5Yy6ZWcQBQzpgJrngYzmoKHljLoFATFnEAUU6IuN5qKn5qCh5Yy6QUTljLpCMTMFATJnEAUQ6IuN5qKn5qCh5Yy6QuWMugUBM2cWAQICZAIDDxYCHgdWaXNpYmxlZxYCAgEPEA8WBh4NRGF0YVRleHRGaWVsZAUIUk9PTU5BTUUeDkRhdGFWYWx1ZUZpZWxkBQZST09NSUQeC18hRGF0YUJvdW5kZ2QQFRIG5qW85ZCND0HljLowMeWPt+alvCAgIA9B5Yy6MDLlj7fmpbwgICAPQeWMujAz5Y+35qW8ICAgD0HljLowNOWPt+alvCAgIA9B5Yy6MDjlj7fmpbwgICAPQeWMujA55Y+35qW8ICAgD0HljLoxMOWPt+alvCAgIA9C5Yy6MTPlj7fmpbwgICAPROWMujA15Y+35qW8ICAgD0TljLowNuWPt+alvCAgIA9E5Yy6MDnlj7fmpbwgICAPROWMujEw5Y+35qW8ICAgD0TljLowOOWPt+alvCAgIA9E5Yy6MDflj7fmpbwgICAPQeWMujA25Y+35qW8ICAgD0HljLowNeWPt+alvCAgIA9B5Yy6MDflj7fmpbwgICAVEgACNTICNTMCNTQCNTUCNTYCNTcCNTgCNjACNjECNjICNjMCNjQEMjkzNQQyOTM2BDIxOTEEMjE5MgQyMTkzFCsDEmdnZ2dnZ2dnZ2dnZ2dnZ2dnZxYBAgtkAgUPZBYCAgEPEGQQFQEG5qW85bGCFQEAFCsDAWcWAWZkAgcPFgIfAGcWAgIBDxAPFgYfAQUIUk9PTU5BTUUfAgUGcm9vbWlkHwNnZBAViwEG5oi/6Ze0DEQwOS0xMDEgICAgIAxEMDktMTAyICAgICAMRDA5LTEwMyAgICAgDEQwOS0xMDQgICAgIAxEMDktMTA1ICAgICAMRDA5LTEwNiAgICAgDEQwOS0xMDcgICAgIAxEMDktMTA4ICAgICAMRDA5LTEwOSAgICAgDEQwOS0xMTAgICAgIAxEMDktMTExICAgICAMRDA5LTExMiAgICAgDEQwOS0xMTMgICAgIAxEMDktMTE0ICAgICAMRDA5LTExNSAgICAgDEQwOS0xMTYgICAgIAxEMDktMTE3ICAgICAMRDA5LTExOCAgICAgDEQwOS0xMTkgICAgIAxEMDktMTIwICAgICAMRDA5LTEyMSAgICAgDEQwOS0xMjIgICAgIAxEMDktMjAxICAgICAMRDA5LTIwMiAgICAgDEQwOS0yMDMgICAgIAxEMDktMjA0ICAgICAMRDA5LTIwNSAgICAgDEQwOS0yMDYgICAgIAxEMDktMjA3ICAgICAMRDA5LTIwOCAgICAgDEQwOS0yMDkgICAgIAxEMDktMjEwICAgICAMRDA5LTIxMSAgICAgDEQwOS0yMTIgICAgIAxEMDktMjEzICAgICAMRDA5LTIxNCAgICAgDEQwOS0yMTUgICAgIAxEMDktMjE2ICAgICAMRDA5LTIxNyAgICAgDEQwOS0yMTggICAgIAxEMDktMjE5ICAgICAMRDA5LTIyMCAgICAgDEQwOS0yMjEgICAgIAxEMDktMjIyICAgICAMRDA5LTIyNCAgICAgDEQwOS0zMDEgICAgIAxEMDktMzAyICAgICAMRDA5LTMwMyAgICAgDEQwOS0zMDQgICAgIAxEMDktMzA1ICAgICAMRDA5LTMwNiAgICAgDEQwOS0zMDcgICAgIAxEMDktMzA4ICAgICAMRDA5LTMwOSAgICAgDEQwOS0zMTAgICAgIAxEMDktMzExICAgICAMRDA5LTMxMiAgICAgDEQwOS0zMTMgICAgIAxEMDktMzE0ICAgICAMRDA5LTMxNSAgICAgDEQwOS0zMTYgICAgIAxEMDktMzE3ICAgICAMRDA5LTMxOCAgICAgDEQwOS0zMTkgICAgIAxEMDktMzIwICAgICAMRDA5LTMyMSAgICAgDEQwOS0zMjIgICAgIAxEMDktMzI0ICAgICAMRDA5LTQwMSAgICAgDEQwOS00MDIgICAgIAxEMDktNDAzICAgICAMRDA5LTQwNCAgICAgDEQwOS00MDUgICAgIAxEMDktNDA2ICAgICAMRDA5LTQwNyAgICAgDEQwOS00MDggICAgIAxEMDktNDA5ICAgICAMRDA5LTQxMCAgICAgDEQwOS00MTEgICAgIAxEMDktNDEyICAgICAMRDA5LTQxMyAgICAgDEQwOS00MTQgICAgIAxEMDktNDE1ICAgICAMRDA5LTQxNiAgICAgDEQwOS00MTcgICAgIAxEMDktNDE4ICAgICAMRDA5LTQxOSAgICAgDEQwOS00MjAgICAgIAxEMDktNDIxICAgICAMRDA5LTQyMiAgICAgDEQwOS00MjQgICAgIAxEMDktNTAxICAgICAMRDA5LTUwMiAgICAgDEQwOS01MDMgICAgIAxEMDktNTA0ICAgICAMRDA5LTUwNSAgICAgDEQwOS01MDYgICAgIAxEMDktNTA3ICAgICAMRDA5LTUwOCAgICAgDEQwOS01MDkgICAgIAxEMDktNTEwICAgICAMRDA5LTUxMSAgICAgDEQwOS01MTIgICAgIAxEMDktNTEzICAgICAMRDA5LTUxNCAgICAgDEQwOS01MTUgICAgIAxEMDktNTE2ICAgICAMRDA5LTUxNyAgICAgDEQwOS01MTggICAgIAxEMDktNTE5ICAgICAMRDA5LTUyMCAgICAgDEQwOS01MjEgICAgIAxEMDktNTIyICAgICAMRDA5LTUyNCAgICAgDEQwOS02MDEgICAgIAxEMDktNjAyICAgICAMRDA5LTYwMyAgICAgDEQwOS02MDQgICAgIAxEMDktNjA1ICAgICAMRDA5LTYwNiAgICAgDEQwOS02MDcgICAgIAxEMDktNjA4ICAgICAMRDA5LTYwOSAgICAgDEQwOS02MTAgICAgIAxEMDktNjExICAgICAMRDA5LTYxMiAgICAgDEQwOS02MTMgICAgIAxEMDktNjE0ICAgICAMRDA5LTYxNSAgICAgDEQwOS02MTYgICAgIAxEMDktNjE3ICAgICAMRDA5LTYxOCAgICAgDEQwOS02MTkgICAgIAxEMDktNjIwICAgICAMRDA5LTYyMSAgICAgDEQwOS02MjIgICAgIAxEMDktNjI0ICAgICAQ5LiA5bGC5rW05a6kICAgIBWLAQAEMjAxMwQyMDE0BDIwMTUEMjAxNgQyMDE3BDIwMTgEMjAxOQQyMDIwBDIwMjEEMjAyMgQyMDIzBDIwMjQEMjAyNQQyMDI2BDIwMjcEMjAyOAQyMDI5BDIwMzAEMjAzMQQyMDMyBDIwMzMEMjAzNAQyMDM3BDIwMzgEMjAzOQQyMDQwBDIwNDEEMjA0MgQyMDQzBDIwNDQEMjA0NQQyMDQ2BDIwNDcEMjA0OAQyMDQ5BDIwNTAEMjA1MQQyMDUyBDIwNTMEMjA1NAQyMDU1BDIwNTYEMjA1NwQyMDU4BDIwNjAEMjA2MwQyMDY0BDIwNjUEMjA2NgQyMDY3BDIwNjgEMjA2OQQyMDcwBDIwNzEEMjA3MgQyMDczBDIwNzQEMjA3NQQyMDc2BDIwNzcEMjA3OAQyMDc5BDIwODAEMjA4MQQyMDgyBDIwODMEMjA4NAQyMDg2BDIwOTAEMjA5MQQyMDkyBDIwOTMEMjA5NAQyMDk1BDIwOTYEMjA5NwQyMDk4BDIwOTkEMjEwMAQyMTAxBDIxMDIEMjEwMwQyMTA0BDIxMDUEMjEwNgQyMTA3BDIxMDgEMjEwOQQyMTEwBDIxMTEEMjExMwQyMTE2BDIxMTcEMjExOAQyMTE5BDIxMjAEMjEyMQQyMTIyBDIxMjMEMjEyNAQyMTI2BDIxMjcEMjEyOAQyMTI5BDIxMzAEMjEzMQQyMTMyBDIxMzMEMjEzNAQyMTM1BDIxMzYEMjEzNwQyMTM4BDIxNDAEMjE0MwQyMTQ0BDIxNDUEMjE0NgQyMTQ3BDIxNDgEMjE0OQQyMTUwBDIxNTEEMjE1MgQyMTUzBDIxNTQEMjE1NQQyMTU2BDIxNTcEMjE1OAQyMTU5BDIxNjAEMjE2MQQyMTYyBDIxNjMEMjE2NAQyMTY2BDIxNzUUKwOLAWdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dkZBgBBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WBAUEYnV5UgUFdXNlZFIFDEltYWdlQnV0dG9uMQUMSW1hZ2VCdXR0b24yw6pCyBcZlhCnJok5y9Kf0cba4YeHwXNtcUjLGaH4miw='
    # drxiaoqu = ''
    # drlouming = ''
    # drfangjian = ''
    # radio = ''
    #
    ImageButton1x = '43'
    ImageButton1y = '28'

    default_data = {'__EVENTTARGET': '',
                    '__EVENTARGUMENT': '',
                    '__LASTFOCUS': '',
                    '__VIEWSTATE': VIEWSTATE,
                    'drxiaoqu': drxiaoqu,
                    'drlouming': drlouming,
                    'drfangjian': drfangjian,
                    'radio': radio,
                    'ImageButton1.x': ImageButton1x,
                    'ImageButton1.y': ImageButton1y,
                    }
    userRecord_data = {'__VIEWSTATE': '/wEPDwULLTE0ODczMDEwNjlkZBlg1O5faxP/z435MYnGH249r00eW+BbwGL29NzizhTq',
                       '__EVENTVALIDATION': '/wEWBALc36PcDwLE2qDzBgKG+5Y+AouTwe8Che6m/o1/82BbaZcxbpZlxm8QKQMyOdJUvvup/LihY9M=',
                       'txtstart': txtstart,
                       'txtend': txtend,
                       'btnser': '查询',
                       }

    # post传入宿舍号等信息，必须，req是点击登录按钮之后的响应
    req = session.post(default_url, data=default_data)

    # post传入日期参数
    req2 = session.post(userRecord_url, data=userRecord_data)
    print(req2.text)

    soup = BeautifulSoup(req2.content, 'lxml')
    # 返回列表迭代器
    pageer = soup.find(attrs={'class': 'pageControl'}).children
    # print(pageer)

    # 找到尾页地址
    for i in pageer:
        if i.string == '尾页':
            print(i['href'])




    page = '2'
    req3 = session.get(userRecord_url, params={'p': page})
    # print(req3.text)

    session.close()


if __name__ == '__main__':
    get_html(txtstart='2017-01-23')
